# wood_boeing:
#   color: [0.6, 0.6, 0.65, 0.01]
#   prior: [0, 0, 0, 0, 0, 0]
#   initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#   localization_object: wood_boeing
#   # localization_object_cad: package://custom_ray_trace/sdf/wood_boeing.stl
#   # localization_object_filepath: ($find custom_ray_trace)/sdf/wood_boeing.stl 
#   particle_frame: [0, 0.0, 0, 0, 0, 0]

front_datum:
  color: [0, 0.5, 0.5, 0.2]
  # prior: [0, 0.0, 0, 0, 0, 0]
  # initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  prior: [0, -0.023, 0, 0, 0, 0.03]
  initial_uncertainties: [0.0, 0.03, 0.0, 0.0, 0.0, 0.05]
  localization_object: front_datum
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]

top_datum:
  color: [0.5, 0, 0.5, 0.2]
  # prior: [0, 0, 0, 0, 0, 0]
  # initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  prior: [0, 0, 0.025, 0.0, 0.04, 0]
  initial_uncertainties: [0.0, 0.0, 0.03, 0.01, 0.05, 0.0]
  localization_object: top_datum
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]

right_datum:
  color: [0, 0, 1, 0.2]
  # prior: [0, 0, 0, 0, 0, 0]
  # initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  prior: [0.02, 0, 0, 0, -0.005, 0.01]
  initial_uncertainties: [0.03, 0.0, 0.0, 0.0, 0.02, 0.02]
  localization_object: right_datum
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]

left_datum:
  color: [0.5, 0.5, 0, 0.2]
  # prior: [0, 0, 0, 0, 0, 0]
  # initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  prior: [0.005, 0, 0, 0, 0.005, -0.01]
  initial_uncertainties: [0.01, 0.0, 0.0, 0.0, 0.02, 0.02]
  localization_object: left_datum
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]

bottom_datum:
  color: [0.5, 0, 0.5, 0.2]
  # prior: [0, 0, 0, 0, 0, 0]
  # initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  prior: [0, 0, 0.005, -0.01, 0.01, 0]
  initial_uncertainties: [0.0, 0.0, 0.02, 0.02, 0.02, 0.0]
  localization_object: bottom_datum
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]

J1_section:
  color: [0.5, 0.5, 0.5, 0.2]
  # prior: [0, 0, 0, 0, 0, 0]
  # initial_uncertainties: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  prior: [0.01, 0.005, -0.003, 0.01, 0, -0.01]
  initial_uncertainties: [0.01, 0.01, 0.01, 0.02, 0.02, 0.02]
  localization_object: J1_section
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]

hole:
  color: [0, 1, 0, 0.5]
  localization_object: hole
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, 0]