wood_boeing:
  color: [0.6, 0.6, 0.65, 0.01]
  initial_uncertainties: [0.01, 0.01, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: wood_boeing
  # localization_object_cad: package://custom_ray_trace/sdf/wood_boeing.stl
  # localization_object_filepath: ($find custom_ray_trace)/sdf/wood_boeing.stl 
  particle_frame: [0, 0.0, 0, 0, 0, 0]

right_datum:
  color: [0, 0, 1, 0.2]
  initial_uncertainties: [0.01, 0.0001, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: right_datum
  # localization_object_cad: package://custom_ray_trace/sdf/right_datum.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/right_datum.stl # 
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, 0, 0, 0, 0, -1.570796]

left_datum:
  color: [0.5, 0.5, 0, 0.2]
  initial_uncertainties: [0.01, 0.0001, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: left_datum
  # localization_object_cad: package://custom_ray_trace/sdf/top_datum.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/top_datum.stl 
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [1.2192, 0, 0, 0, 0, 1.570796]

top_datum:
  color: [0.5, 0, 0.5, 0.2]
  initial_uncertainties: [0.01, 0.0001, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: top_datum
  # localization_object_cad: package://custom_ray_trace/sdf/top_datum.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/top_datum.stl 
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [0, -0.063, 0.23, -1.570796, 0, 0]
  
front_datum:
  color: [0, 0.5, 0.5, 0.2]
  initial_uncertainties: [0.01, 0.0001, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: front_datum
  # localization_object_cad: package://custom_ray_trace/sdf/top_datum.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/top_datum.stl 
  particle_frame: [0, 0, 0, 0, 0, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  true_state: [1.2192, -0.025, 0.014, 0, 0, 3.141593]
